#!/bin/sh

COMMON_LIB=$HOME/applications/PaaS-BE-AM
#echo -----------------------------------------COMMON_LIB $COMMON_LIB
export COMMON_LIB

for file in ${COMMON_LIB}/**/*.jar;
do CP=${CP}:$file;
done

CLASSPATH="${CP}"
export CLASSPATH
#echo $CLASSPATH
export JAVA_OPTIONS=" -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=10"
export MEM_ARGS="-Xms128m -Xmx512m"

${JAVA_HOME}/bin/java ${MEM_ARGS}  ${JAVA_OPTIONS} com.ai.paas.ipaas.DubboServiceStart $1