---
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  vars:
  tasks:
    - name: copy haproxy.cfg bak
      command: cp -f /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
      sudo: yes
    - name: copy haproxy.cfg logbak
      command: cp -f /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy{{ haproxydate }}.bak
      sudo: yes
    - name: delete oldservername acl anyway
      command: sed -i '/\<{{ oldservername }}\>/d' /etc/haproxy/haproxy.cfg
      sudo: yes
    - name: reload haproxy service
      command: /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg
      sudo: yes

