---
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  vars:
  tasks:
    - name: copy haproxy.cfg.bak back
      command: cp -f /etc/haproxy/haproxy.cfg.bak /etc/haproxy/haproxy.cfg
      sudo: yes
    - name: reload haproxy service
      command: /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg
      sudo: yes

